# Generated by Django 3.1.2 on 2020-10-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacaptureapp', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
