# Generated by Django 3.1.2 on 2020-10-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacaptureapp', '0003_node_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
