# Generated by Django 3.1.2 on 2020-10-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacaptureapp', '0005_auto_20201028_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='date_time_stored',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
